### PR TITLE
Revert

### LINKED ISSUE #134: Erroneous readings
I have had Victron integration working perfectly for last few months.  But noticed that recently (can't pinpoint which version, but currently running ESPHome 2023.11.2) I started getting erroneous readings.  Such as battery voltage being 0.0V, when its not in reality and checking via bluetooth app the battery is reading correctly.  When looking at the logs I get unhandled property errors such as the one listed here:

[13:06:37][D][victron:1024]: Unhandled property: VPV
H19 3515
[13:08:13][D][victron:1024]: Unhandled property: CVPV 29170

I thought maybe my ESP8266 is misbehaving so I tried another but same results.  I have two different Victron MPPT controllers and both appear to be doing this.  Did something in new ESPHome versions change and is breaking this now?

### PR DESCRIPTION
**Pull request by wozz**
reverts #133 
fixes #134 
reopens #132

### CODE REVIEW

**Comment by syssi** [comment]
You have merged the remote tracking branch origin into your fork after reverting. This did revert the revert again. ;-)

**Comment by wozz** [comment]
it didn't show a diff before that either. let me revert it again now

**Comment by syssi** [comment]
See #138.

**Comment by syssi** [comment]
Could you prepare a new pull request marked as draft to contribute your async serial handling again? Thanks in advance!

**Pull request closed without merging**
